export const IconTypes = {
    READ : "READ",
    TO_READ : "TO_READ",
    HIGH_PRIORITY : "HIGH_PRIORITY",
    MEDIUM_PRIORITY : "MEDIUM_PRIORITY",
    LOW_PRIORITY : "LOW_PRIORITY",
    FAVOURITE : "FAVOURITE",
    NOT_FAVOURITE : "NOT_FAVOURITE"
}
